/* Colors */
export const Color = {
  text: '#222222',
  white: '#ffffff',
  accent: '#ffffff',
  highlight: '#FF144D',
  contrast: '#222222',
  primary: '#441AB4',
  secondary: 'red',
  normal: '#ffffff',
  grayLight: '#F4F4F4',
  grayHighlight: '#E5E5E5',
  gray: '#C0C0C0',
  grayDark: '#121212',
  violetDark: '#2C2645',
  violet: '#D80D8D',
  notificationNormal: '#cce5ff',
  notificationSuccess: '#d4edda',
  notificationAlert: '#fff3cd',
  notificationDanger: '#f8d7da',
  red: 'red',
  green: '#60d18d',
  greenLight: '#DFF7F2',
};